### ISSUE TITLE
trec_eval on 64 bit Linux machines

### ISSUE THREAD

**Issue by umazalakain** [terrier-org/terrier-core#22] opened 2019-02-23 20:37 UTC
When I run `./bin/terrier batchevaluate -q ../TopicsQrels/HP04/qrels` I get the following traceback:

```
Setting TERRIER_HOME to /home/uma/devel/uni/ir/ex2/terrier-project-5.1
Setting JAVA_HOME to /home/uma/.nix-profile
20:30:06.105 [main] INFO  o.t.evaluation.TrecEvalEvaluation - Evaluating result file: /home/uma/devel/uni/ir/ex2/terrier-project-5.1/var/results/PL2_0.res
Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Cannot run program "/tmp/jtrec_eval2842220965852518824/trec_eval3972474431911863829.exe": error=2, No such file or directory
        at uk.ac.gla.terrier.jtreceval.trec_eval.runAndGetOutput(trec_eval.java:151)
        at org.terrier.evaluation.TrecEvalEvaluation.evaluate(TrecEvalEvaluation.java:101)
        at org.terrier.evaluation.BatchEvaluationCommand.run(BatchEvaluationCommand.java:111)
        at org.terrier.applications.CLITool$CLIParsedCLITool.run(CLITool.java:155)
        at org.terrier.applications.CLITool.main(CLITool.java:316)
Caused by: java.io.IOException: Cannot run program "/tmp/jtrec_eval2842220965852518824/trec_eval3972474431911863829.exe": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at uk.ac.gla.terrier.jtreceval.trec_eval.runAndGetOutput(trec_eval.java:141)
        ... 4 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 5 more
```

From what I understand, what's happening is exactly the issue described in http://terrier.org/issues/browse/TR-465, which is supposedly solved. Still, I run into this with Terrier 5.1. The documentation also says "For unsupported platforms, Terrier also includes a legacy Java evaluation package for evaluating results of TREC adhoc and named-page finding tasks." but seemingly this is not the case.

**Comment by umazalakain** [comment] 2019-02-24 12:13
Compiling trec_eval (https://github.com/usnistgov/trec_eval) works :-)

**Comment by cmacdonald** [comment] 2019-02-24 17:43
Exactly what platform is this on? It works on the lab machines and many other Linux servers that are all 64 bit. We provide a working lab environment, so in doubt you can use that. 

trec_eval is indeed a 3rd party tool that we provide (precompiled for a number of standard platforms) for convenience as part of Terrier - in case of doubt you can indeed recompile it yourself to match your platform.

**Comment by umazalakain** [comment] 2019-02-24 18:01
I'm running NixOS, with the following kernel:

```
Linux athekaleun 4.19.12 #1-NixOS SMP Fri Dec 21 13:15:25 UTC 2018 x86_64 GNU/Linux
```

On the bright part, trec_eval is very straightforward to compile.

On a related note: on some systems (like NixOS), bash is not in 
`/bin/bash`. I believe `/usr/bin/env bash` is usually used for greater 
flexibility.

**Comment by cmacdonald** [comment] 2019-02-24 18:40
Let's be honest, NixOS a fairly unusual choice of OS, and probably didn't warrant a forum post to the entire class.
 I will note the point about `/usr/bin/env bash` - I would need to check that works in Cygwin.
To complete the documentation of your OS, can you run `ldd` on your compiled trec_eval and record the output here please.

**Comment by umazalakain** [comment] 2019-02-24 18:59
I wasn't sure if my system being NixOS had something to do with it, but now that 
I think of it it ss obvious that it does (see the output of ldd).  And yeah, 
NixOS is fairly rare, I should have posted here first -- or, if I knew what I 
know now, not posted at all.

Just to confirm the issue is with NixOS, here is the output of ldd:
      linux-vdso.so.1 (0x00007ffebcfef000)
      libm.so.6 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libm.so.6 (0x00007f5131897000)
      libc.so.6 => /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/libc.so.6 (0x00007f51314e3000)
      /nix/store/0fv2lnbr02qzh3l387rvd6vl8443mpq7-glibc-2.27/lib/ld-linux-x86-64.so.2 => /nix/store/pr73kx0cdszbv9iw49g8dzi0nqxfjbx2-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007f5131c2c000)

I think NixOS uses a modified gcc so that those libraries are found automatically.

**Comment by cmacdonald** [comment] 2019-02-25 10:32
Finally, for comparison, can you download this binary - https://github.com/terrierteam/jtreceval/blob/master/src/main/resources/trec_eval-linux-amd64 - and run ldd on it. The problem is usually that shared libraries cannot be found.

Craig

**Comment by umazalakain** [comment] 2019-02-25 11:55
I don't know what kind of magic is going on here, but when I run ldd on 
the downloaded trac_eval-linux-amd64 the libraries seem to be 
automatically discovered:

```
linux-vdso.so.1 (0x00007fff57173000)
libm.so.6 => /nix/store/pr73kx0cdszbv9iw49g8dzi0nqxfjbx2-glibc-2.27/lib/libm.so.6 (0x00007fd6b7c8f000)
libc.so.6 => /nix/store/pr73kx0cdszbv9iw49g8dzi0nqxfjbx2-glibc-2.27/lib/libc.so.6 (0x00007fd6b78db000)
/lib64/ld-linux-x86-64.so.2 => /nix/store/pr73kx0cdszbv9iw49g8dzi0nqxfjbx2-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007fd6b8024000)
```

Yet, I cannot run the binary. I'll ask a friend who knows about NixOS.

**Comment by cmacdonald** [comment] 2019-02-25 14:53
Can you paste the exact error message when you run the trec_eval-linux-amd64 binary?

The linux library linker (ld) in a distribution is configured to know where to look for the libraries. Its either about those libraries, or the particular library version.

**Comment by cmacdonald** [comment] 2019-04-24 22:11
No further update, closing as cannot reproduce.

**Closed as completed by cmacdonald** 2019-04-24 22:11 UTC
